language: python
cache: pip
dist: bionic

python:
  - 3.6
  - 3.7
  - 3.8

addons:
  apt:
    update: true
    packages:
      - plantuml

before_install: pip install poetry

install: poetry install


script:
  - make lint
  - make test
  - make docs


jobs:
  include:
    if: type = cron
    script: make safety


deploy:
  - provider: pages
    on:
      branch: master
      python: '3.8'
    skip_cleanup: true
    keep-history: true
    local_dir: docs/_build/html/
    github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure

  - provider: script
    on:
      tags: true
      python: '3.8'
    # Uses Twine, requires  environmental variables:
    # TWINE_USERNAME, TWINE_PASSWORD
    provider: script
