sudo: false

language: python

dist: xenial

python:
  - "3.6"
  - "3.7"

install: pip install tox-travis

jobs:
  include:
    - stage: test
      script: make tox

    - stage: build-html-docs
      script: make docs
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
        keep-history: true
        on:
          branch: master
          local_dir: _build/html/
