sudo: false

language: python

dist: bionic

python:
  - '3.6'
  - '3.7'
  - '3.8'
  - 'pypy3'

addons:
  apt:
    update: true
    packages:
      - plantuml

install:
  - pip install -r requirements.test.txt

script:
  - make lint
  - make test
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then make docs; fi


deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  local_dir: docs/_build/html/
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  on:
    branch: master
    python: '3.8'
