sudo: false

language: python

dist: xenial

python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.dev.txt

script:
  - make test
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7'* ]]; then make docs; fi



deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
    local_dir: _build/html/
