sudo: false

language: python

dist: xenial

python:
  - '3.6'
  - '3.7'

install:
  - pip install -r requirements.test.txt

script:
  - make flake8
  - make test
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then make docs; fi



deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  local_dir: docs/_build/html/
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  on:
    branch: master
    python: '3.7'


