language: python
cache: pip
dist: bionic

python:
  - 3.6
  - 3.7
  - 3.8

addons:
  apt:
    update: true
    packages:
      - graphviz
      - plantuml

before_install: pip install poetry

install: poetry install


script:
  - make lint
  - make test
  - make doctest


jobs:
  include:
    if: type = cron
    script: make safety


deploy:
  - provider: script
    on:
      tags: true
      python: '3.8'
    # Uses Twine, requires  environmental variables:
    # TWINE_USERNAME, TWINE_PASSWORD
    script: make deploy
